# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smart_meter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'smart_meter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11smart_meter.proto\x12\nsmartmeter\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n\tFlexValue\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xbf\x02\n\x03GDR\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x06status\x18\x02 \x01(\x0e\x32\x12.smartmeter.Status\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x06values\x18\x04 \x03(\x0b\x32\x1b.smartmeter.GDR.ValuesEntry\x12\x33\n\nflexValues\x18\x05 \x03(\x0b\x32\x1f.smartmeter.GDR.FlexValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x1aH\n\x0f\x46lexValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.smartmeter.FlexValue:\x02\x38\x01\"\x82\x01\n\x04GDRs\x12(\n\x04GDRs\x18\x01 \x03(\x0b\x32\x1a.smartmeter.GDRs.GDRsEntry\x12\x12\n\nconfigUuid\x18\x02 \x01(\t\x1a<\n\tGDRsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.smartmeter.GDR:\x02\x38\x01*Q\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x12\n\x0eSTATUS_WARNING\x10\x02\x12\x10\n\x0cSTATUS_ERROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_meter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GDR_VALUESENTRY']._loaded_options = None
  _globals['_GDR_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_GDR_FLEXVALUESENTRY']._loaded_options = None
  _globals['_GDR_FLEXVALUESENTRY']._serialized_options = b'8\001'
  _globals['_GDRS_GDRSENTRY']._loaded_options = None
  _globals['_GDRS_GDRSENTRY']._serialized_options = b'8\001'
  _globals['_STATUS']._serialized_start=563
  _globals['_STATUS']._serialized_end=644
  _globals['_FLEXVALUE']._serialized_start=66
  _globals['_FLEXVALUE']._serialized_end=106
  _globals['_GDR']._serialized_start=109
  _globals['_GDR']._serialized_end=428
  _globals['_GDR_VALUESENTRY']._serialized_start=309
  _globals['_GDR_VALUESENTRY']._serialized_end=354
  _globals['_GDR_FLEXVALUESENTRY']._serialized_start=356
  _globals['_GDR_FLEXVALUESENTRY']._serialized_end=428
  _globals['_GDRS']._serialized_start=431
  _globals['_GDRS']._serialized_end=561
  _globals['_GDRS_GDRSENTRY']._serialized_start=501
  _globals['_GDRS_GDRSENTRY']._serialized_end=561
# @@protoc_insertion_point(module_scope)
